### ISSUE TITLE
Keeping in sync with aibtcdev-contracts

### ISSUE THREAD

**Issue by whoabuddy** [aibtcdev/agent-tools-ts#77]
While making changes it was definitely hard to keep the two in sync, might be less of a problem following launch but required a lot of `git diff --no-index` and manually reading the output.

Main files that required updates were:
- src/constants.ts for TRAITS
- src/types/index.ts for NetworkTraits

Following that I ended up generating code then comparing that as well.

Maybe a pipeline from contract -> template -> output where Clarinet can help us on both sides?

Trying to avoid subrepo hell but maybe monorepo is a better answer?

Moving on for now!

**Comment by whoabuddy** [comment]
In order to help with this #80 introduced the ability to generate and save the dao contracts to `/generated/{token_symbol}`, folder is ignored by git by default.

```bash
bun run src/stacks-contracts/generate-dao.ts TUE "Tuesday Token" 1000000000 6 "https://bitcoin.org" true
```

The command above would generate the contracts at `/generated/tue`, matching their deployed names:

![image](https://github.com/user-attachments/assets/a1af8b2a-ab16-463d-a6c3-3a655c71ce56)

Taking that a step further, we can have a working `clarinet check` in this directory with a few changes:
- contracts need to use relative references (sugar syntax) where possible, as explicit references tell Clarinet to look on-chain
  - this mainly applies to the `is-dao-or-extension` function
  - any dao contract that calls another at the same deployer can use `.contract_name` instead of the full `'address.contract_name` syntax
- the folder with the contracts needs a `settings/Devnet.toml` file (could copy from root)
- the folder with the contracts needs a Clarinet.toml outlining how all the contracts are connected

Example `clarinet.toml` with `generated/tue` contracts:

```toml
[project]
name = 'aibtcdev-smart-contracts'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'

[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

# external contracts loaded by clarinet

[[project.requirements]]
contract_id = 'ST000000000000000000002AMW42H.pox-4'

[[project.requirements]]
contract_id = 'ST6BBNM7Q8GKDG2FMKRBZJCJ3SE4BWVC1YSF2XKD.aibtcdev-dao-v1'

[[project.requirements]]
contract_id = 'ST6BBNM7Q8GKDG2FMKRBZJCJ3SE4BWVC1YSF2XKD.aibtcdev-dao-traits-v1'

[[project.requirements]]
contract_id = 'ST6BBNM7Q8GKDG2FMKRBZJCJ3SE4BWVC1YSF2XKD.xyk-pool-trait-v-1-2'

[[project.requirements]]
contract_id = 'ST6BBNM7Q8GKDG2FMKRBZJCJ3SE4BWVC1YSF2XKD.xyk-core-v-1-2'

[[project.requirements]]
contract_id = 'ST295MNE41DC74QYCPRS8N37YYMC06N6Q3VQDZ6G1.token-stx-v-1-2'

# dao contracts

[contracts.tue-base-dao]
path = 'tue-base-dao.clar'
clarity_version = 2
epoch = 3.0

[contracts.tue-action-proposals]
path = 'tue-action-proposals.clar'
clarity_version = 2
epoch = 3.0

[contracts.tue-bank-account]
path = 'tue-bank-account.clar'
clarity_version = 2
epoch = 3.0

[contracts.tue-base-bootstrap-initialization]
path = 'tue-base-bootstrap-initialization.clar'
clarity_version = 2
epoch = 3.0

[contracts.tue-core-proposals]
path = 'tue-core-proposals.clar'
clarity_version = 2
epoch = 3.0

[contracts.tue-onchain-messaging]
path = 'tue-onchain-messaging.clar'
clarity_version = 2
epoch = 3.0

[contracts.tue-payments-invoices]
path = 'tue-payments-invoices.clar'
clarity_version = 2
epoch = 3.0

[contracts.tue-stxcity-dex]
path = 'tue-stxcity-dex.clar'
clarity_version = 2
epoch = 3.0

[contracts.tue-stxcity]
path = 'tue-stxcity.clar'
clarity_version = 2
epoch = 3.0

[contracts.tue-token-owner]
path = 'tue-token-owner.clar'
clarity_version = 2
epoch = 3.0

[contracts.tue-treasury]
path = 'tue-treasury.clar'
clarity_version = 2
epoch = 3.0

[contracts.xyk-pool-stx-tue-v-1-1]
path = 'xyk-pool-stx-tue-v-1-1.clar'
clarity_version = 2
epoch = 3.0
```

After those changes `clarinet check` can be run against the generated contracts:
```bash
~/Dev/aibtcdev/agent-tools-ts/generated/tue$ clarinet check
✔ 12 contracts checked
```
